parameters:
    app.vapid_public_key: '%env(VAPID_PUBLIC_KEY)%'
    app.vapid_private_key: '%env(VAPID_PRIVATE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # State Processor pro BeerEntry - nastavuje uživatele při vytváření
    App\State\BeerEntryProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    App\Controller\PushController:
        arguments:
            $vapidPublicKey: '%app.vapid_public_key%'

    App\Service\WebPushService:
        arguments:
            $vapidPublicKey: '%app.vapid_public_key%'
            $vapidPrivateKey: '%app.vapid_private_key%'

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
